services:
  auto-database:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -h localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: ["postgres", "-c", "statement_timeout=30s"]

  auto-redis:
    image: bitnami/redis:6.2
    hostname: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis
    healthcheck:
      test: ["CMD","redis-cli", "-h", "localhost", "ping"]

  auto-influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
       DOCKER_INFLUXDB_INIT_MODE: setup
       DOCKER_INFLUXDB_INIT_USERNAME: admin
       DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
       DOCKER_INFLUXDB_INIT_ORG: myorg
       DOCKER_INFLUXDB_INIT_BUCKET: sensors_logs
       DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}

    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  auto_grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    depends_on:
      - auto-influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true          # allow embedding in iframes
      - GF_AUTH_ANONYMOUS_ENABLED=true             # enable anonymous access (optional)
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer          # anonymous role
      # You can add more Grafana environment variables here if needed
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards

volumes:
  redis_data:
  pg_data:
  influxdb_data:
  grafana_data:
