apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://auto-influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: sensors_logs
    secureJsonData:
      token: yhDXqZa7azf2WhuRxLPm0dpHyMY7T0q8uRirEByN6vPYL5EkG-z6USMv8iUDk9jI8GhSyEuXe3E2_0WvedgUSw==

